stages:
  - test
  - build
  - deploy
lint-test-job:
  image: 'python:3-bullseye'
  stage: test
  script:
    - pip install flake8
    - flake8 sample_service
build-front-end-job:
  stage: build
  image: 'node:lts-bullseye'
  needs:
    - lint-test-job
  variables:
    PUBLIC_URL: 'https://GROUP_NAME.gitlab.io/PROJECT_NAME/'
    REACT_APP_SAMPLE_SERVICE_API_HOST: 'https://WEBSERVICE_NAME.onrender.com'
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
