stages:
  - test
  - build
  - deploy

services:
  - postgres:14.2-bullseye

variables:
  POSTGRES_PASSWORD: test
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres

lint-test-job:
  image: 'python:3-bullseye'
  stage: test
  script:
    - pip install flake8
    - flake8 sample_service
letters-service-test-job:
  image: python:3.10-bullseye
  stage: test
  script:
    - cd letters-service
    - pip install -r requirements.txt
    - python manage.py test


build-front-end-job:
  stage: build
  image: 'node:lts-bullseye'
  needs:
    - lint-test-job
  variables:
    PUBLIC_URL: 'https://GROUP_NAME.gitlab.io/PROJECT_NAME/'
    REACT_APP_SAMPLE_SERVICE_API_HOST: 'https://WEBSERVICE_NAME.onrender.com'
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
