services:
  users-service:
    build:
      context: ./users-service
      dockerfile: ./Dockerfile
    ports:
      - 8080:8000
    volumes:
      - ./users-service:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgres://rsiduqiy:SQZwR4x0gG7cN_aQw_QuxnA9w9nidXI-@kashin.db.elephantsql.com/rsiduqiy
      WAIT_HOSTS: postgres:5432
  letters-service:
    build:
      context: ./letters-service
      dockerfile: ./Dockerfile
    ports:
      - 8090:8000
    volumes:
      - ./letters-service:/app
    environment:
      SIGNING_KEY: 7ea8f8c1d636b6f92b59a46326d9f59da1e09f0c986fbaeacaad64fed817ce6d
      DATABASE_URL: postgres://qguhdady:v_KZXAFST6YPLW42ttXQZVBoFLj2SJ2P@kashin.db.elephantsql.com/qguhdady
      WAIT_HOSTS: postgres:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      SIGNING_KEY: 7ea8f8c1d636b6f92b59a46326d9f59da1e09f0c986fbaeacaad64fed817ce6d
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
      REACT_APP_USERS_API_HOST: http://localhost:8080
      REACT_APP_LETTERS_API_HOST: http://localhost:8090
