services:
  # A Docker web service
  - type: web
    name: letters
    env: docker
    branch: john-deployment # optional (defaults to master)
    rootDir: letters-service
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
  # # A Python cron job that runs every hour
  # - type: cron
  #   name: date
  #   env: python
  #   schedule: "0 * * * *"
  #   buildCommand: "true" # ensure it's a string
  #   startCommand: date
  #   repo: https://github.com/render-examples/docker.git # optional
  # # A static site
  # - type: web
  #   name: my blog
  #   env: static
  #   buildCommand: yarn build
  #   staticPublishPath: ./build
  #   pullRequestPreviewsEnabled: true # optional
  #   buildFilter:
  #     paths:
  #     - src/**/*.js
  #     ignoredPaths:
  #     - src/**/*.test.js
  #   headers:
  #     - path: /*
  #       name: X-Frame-Options
  #       value: sameorigin
  #   routes:
  #     - type: redirect
  #       source: /old
  #       destination: /new
  #     - type: rewrite
  #       source: /a/*
  #       destination: /a

databases:
  - name: elephant
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
    ipAllowList: # optional (defaults to allow all)
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home

  - name: private database
    databaseName: private
    ipAllowList: [] # only allow internal connections


envVarGroups:
  - name: conc-settings
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true
      - key: USER_PROVIDED_SECRET
        sync: false
  - name: stripe
    envVars:
      - key: STRIPE_API_URL
        value: https://api.stripe.com/v2